defaults:
  - _self_

mode: train
checkpoint: null #checkpoint.pt
device: cuda
epochs: 300
save_period: 20

data:
  tree:
    depth: 4
    branching: 3
    k: 0.8
    L0: 1.
    root_angle: 0.5 # 0.5*pi
    fan: 1.
    sector_decay: 0.9
    gap_ratio: 0.07
  sampler:
    pre_sample: 0
    batch_size: 2000
    batches_per_epoch: 500
    beta_alpha: 3.0
    beta_beta: 3.0
    s: 0.008

dataloader:
  num_workers: 4

sampler:
  num_steps: 200
  cfg_omega: 1

optim:
  lr: 3e-4

logging:
  n_loss_bins: 10

model:
  in_dim: 3
  condition_depth: ${data.tree.depth}
  condition_branch: ${data.tree.branching}
  out_dim: 2
  hidden_dim: 128
  num_layers: 4
